import { NextResponse } from "next/server";
import { buildCampaignSchedule, calculateCampaignHealth, smartSelectProducts, writeCampaignLog } from "../../../lib/campaigns";
import { nowISTISOString } from "../../../lib/istDate";
import { campaignsSetupError, isCampaignSchemaError, loadCampaign, loadProducts, requireCampaignRequest } from "../_shared";

export async function POST(request) {
    const auth = await requireCampaignRequest(request);
    if (auth.errorResponse) return auth.errorResponse;
    const { user, supabase } = auth;

    try {
        const body = await request.json().catch(() => ({}));
        const campaign = await loadCampaign(supabase, user.id, body.campaignId);
        if (!campaign) return NextResponse.json({ error: "Campaign not found." }, { status: 404 });

        const allProducts = await loadProducts(supabase, user.id);
        const selected = Array.isArray(body.productIds) && body.productIds.length
            ? allProducts.filter((product) => body.productIds.includes(product.id))
            : smartSelectProducts(allProducts, 20);
        if (!selected.length) return NextResponse.json({ error: "Upload products first. ORVA needs inventory to create campaigns." }, { status: 400 });

        await supabase.from("campaign_items").delete().eq("campaign_id", campaign.id).eq("client_id", user.id).neq("status", "published");
        const items = buildCampaignSchedule({ campaign, products: selected });
        const { score, recommendations } = calculateCampaignHealth(items, selected);
        const { data: inserted, error } = await supabase.from("campaign_items").insert(items).select("*");
        if (error) {
            if (isCampaignSchemaError(error)) return NextResponse.json({ error: campaignsSetupError() }, { status: 503 });
            throw error;
        }
        await supabase
            .from("campaigns")
            .update({ status: "generated", health_score: score, updated_at: nowISTISOString() })
            .eq("id", campaign.id)
            .eq("client_id", user.id);

        await Promise.all((inserted || []).map((item) => writeCampaignLog(supabase, {
            campaign_item_id: item.id,
            action: "generated",
            actor_id: user.id,
            note: "Generated by ORVA campaign builder.",
        }).catch(() => null)));

        return NextResponse.json({
            message: "ORVA built your campaign calendar.",
            campaign: { ...campaign, status: "generated", health_score: score },
            items: inserted || [],
            health: { score, recommendations },
        }, { status: 201 });
    } catch (error) {
        if (isCampaignSchemaError(error)) return NextResponse.json({ error: campaignsSetupError() }, { status: 503 });
        return NextResponse.json({ error: error.message || "Could not generate campaign." }, { status: 500 });
    }
}
